services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    network_mode: host
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  config-server:
    build: ./config-server
    container_name: config-server
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:///config-repo/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8762/eureka/
    volumes:
      - ./config-repo:/config-repo

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    network_mode: host
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: health_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  patient-service:
    build: ./patient-service
    container_name: patient-service
    network_mode: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/health_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: default

  api-gateway:
    build: ./api-gateway/api-gateway
    container_name: api-gateway
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: default

volumes:
  postgres_data: