
server:
  port: 8888 # The default port for Spring Cloud Config

spring:
  application:
    name: config-server # Name to register with Eureka
  profiles:
    active: native # Tells the server to read from the local file system
  cloud:
    config:
      server:
        native:
          # ? IMPORTANT: Update this path to the ABSOLUTE path on your Ubuntu machine
          search-locations: file:///home/danish/Downloads/spring-projects/healthcare-microservices/config-repo/

# Config server also registers itself with Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Use localhost for its own registration
  instance:
    instance-id: ${spring.application.name}:${instance_id:${random.value}}